# Generated by Django 6.0.2 on 2026-02-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500)),
                ('ranking_mode', models.CharField(choices=[('relevance', 'Relevance'), ('open_access', 'Open Access Only'), ('best_match', 'Best Match')], default='relevance', max_length=20)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='Research_AI_created_e9d654_idx'), models.Index(fields=['ranking_mode'], name='Research_AI_ranking_44cab4_idx')],
            },
        ),
    ]
