# Generated by Django 6.0.3 on 2026-03-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research_AI_Assistant', '0003_remove_querylog_research_ai_used_de_55b67b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('total_response_time', models.FloatField(default=0.0)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_failure', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('reliability_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-reliability_score', '-successful_requests'],
                'indexes': [models.Index(fields=['model_name'], name='Research_AI_model_n_8cb651_idx'), models.Index(fields=['reliability_score'], name='Research_AI_reliabi_6e83d5_idx'), models.Index(fields=['is_active'], name='Research_AI_is_acti_705bf3_idx'), models.Index(fields=['last_success'], name='Research_AI_last_su_76f13a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelReliability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tier', models.CharField(choices=[('primary', 'Primary - Most Reliable'), ('secondary', 'Secondary - Good Performance'), ('emergency', 'Emergency - Last Resort'), ('disabled', 'Disabled - Not Available')], default='secondary', max_length=20)),
                ('priority', models.PositiveIntegerField(default=50)),
                ('custom_temperature', models.FloatField(blank=True, null=True)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('circuit_breaker_threshold', models.PositiveIntegerField(default=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tier', 'priority', 'model_name'],
                'indexes': [models.Index(fields=['tier', 'priority'], name='Research_AI_tier_2c5c34_idx'), models.Index(fields=['model_name'], name='Research_AI_model_n_0f43d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('request_type', models.CharField(choices=[('summary', 'Paper Summary'), ('title', 'Title Generation'), ('other', 'Other')], max_length=20)),
                ('success', models.BooleanField()),
                ('response_time', models.FloatField()),
                ('response_length', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_query_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'created_at'], name='Research_AI_model_n_09cb3a_idx'), models.Index(fields=['success'], name='Research_AI_success_5868e6_idx'), models.Index(fields=['request_type'], name='Research_AI_request_a6761c_idx'), models.Index(fields=['user_query_hash'], name='Research_AI_user_qu_3a51a6_idx')],
            },
        ),
    ]
