# Generated by Django 6.0.3 on 2026-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research_AI_Assistant', '0004_modelperformance_modelreliability_responselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelperformance',
            name='format_compliance_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelperformance',
            name='format_compliance_passed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelperformance',
            name='format_compliance_score',
            field=models.FloatField(default=0.0),
        ),
    ]
