# Generated by Django 6.0.5 on 2026-06-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research_AI_Assistant', '0005_modelperformance_format_compliance_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openalex_id', models.CharField(max_length=100, unique=True)),
                ('pdf_url', models.URLField(max_length=500)),
                ('image_paths', models.JSONField(default=list)),
                ('markdown_content', models.TextField()),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_success', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
