# Generated by Django 6.0.3 on 2026-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research_AI_Assistant', '0006_paperpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responselog',
            name='request_type',
            field=models.CharField(choices=[('summary', 'Paper Summary'), ('title', 'Title Generation'), ('paper qa', 'Paper Q&A'), ('other', 'Other')], max_length=20),
        ),
    ]
