# Generated by Django 6.0.5 on 2026-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research_AI_Assistant', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpdf',
            name='qa_chunk_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperpdf',
            name='qa_chunks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paperpdf',
            name='qa_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paperpdf',
            name='qa_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperpdf',
            name='qa_source_pdf_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
